### PR TITLE
Update Readme. Fix wrong link for IC cutout

### PR DESCRIPTION
**Pull request by archyposada**
Added links to getting started guides and changed name from docs to reference

### CODE REVIEW

**Comment by archyposada** [comment]
Hi Sudipta, I made another PR to finish those changes from last week. I found an old link in the IC section so i fixed that as well

**Comment by khound** [comment]
Looks good. I noticed the IC link and actually is fixed with the current doc. So it's no more the old link. Please pull the latest before you merge. I think i made some changes.

**Comment by khound** [comment]
👍

**Comment by archyposada** [comment]
Awesome! I must be clicking on an old link. Thanks for taking care of that 😊

**Review by archyposada — COMMENTED** [review]
Here are the changes I would like to make

**Pull request closed without merging**
